# Generated by Django 3.0.8 on 2020-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('squares', models.IntegerField()),
                ('deck_size', models.IntegerField()),
                ('deck_list', models.CharField(max_length=1000)),
                ('sequence', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=100)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
